package nu.hex.mediatype;

/**
 *
 * DO NOT MODIFY! This interface is autogenerated.
 *
 * Changes done here will be owerwritten the next time the project runs.
 *
 * To add mediatypes or edit them, run this project and use the editor.
 *
 * If the MTD is manually edited, run the project and use the update button.
 *
 * To remove a mediatype, remove it manually from the MTD file.
 *
 */
public interface CommonMediaType {

    /**
     * Dart files<br>
     *
     * <br>
     * MediaType: <i>application/dart</i>
     * <br>
     * FileSuffix: <i>.dart</i>
     */
    public static final String APPLICATION_DART = "application/dart";
    /**
     * Gzip, Defined in RFC 6713<br>
     *
     * <br>
     * MediaType: <i>application/gzip</i>
     * <br>
     * FileSuffix: <i>.gz, .gzip</i>
     */
    public static final String APPLICATION_GZIP = "application/gzip";
    /**
     * ECMAScript/JavaScript<br>
     *
     * Defined in RFC 4329<br>
     *
     * <br>
     * MediaType: <i>application/javascript</i>
     * <br>
     * FileSuffix: <i>.js</i>
     */
    public static final String APPLICATION_JAVASCRIPT = "application/javascript";
    /**
     * JavaScript Object Notation JSON<br>
     *
     * Defined in RFC 4627<br>
     *
     * <br>
     * MediaType: <i>application/json</i>
     * <br>
     * FileSuffix: <i>.json</i>
     */
    public static final String APPLICATION_JSON = "application/json";
    /**
     * Microsoft Word files<br>
     *
     * <br>
     * MediaType: <i>application/msword</i>
     * <br>
     * FileSuffix: <i>.doc</i>
     */
    public static final String APPLICATION_MSWORD = "application/msword";
    /**
     * Ogg, a multimedia bitstream container format<br>
     *
     * Defined in RFC 5334<br>
     *
     * <br>
     * MediaType: <i>application/ogg</i>
     * <br>
     * FileSuffix: <i>.ogg</i>
     */
    public static final String APPLICATION_OGG = "application/ogg";
    /**
     * Portable Document Format, PDF has been in use for document exchange on the Internet since 1993<br>
     *
     * Defined in RFC 3778<br>
     *
     * <br>
     * MediaType: <i>application/pdf</i>
     * <br>
     * FileSuffix: <i>.pdf</i>
     */
    public static final String APPLICATION_PDF = "application/pdf";
    /**
     * PostScript<br>
     *
     * Defined in RFC 2046<br>
     *
     * <br>
     * MediaType: <i>application/postscript</i>
     * <br>
     * FileSuffix: <i>.ps</i>
     */
    public static final String APPLICATION_POSTSCRIPT = "application/postscript";
    /**
     * Resource Description Framework<br>
     *
     * Defined by RFC 3870<br>
     *
     * <br>
     * MediaType: <i>application/rdf+xml</i>
     * <br>
     * FileSuffix: <i>.rdf</i>
     */
    public static final String APPLICATION_RDF_XML = "application/rdf+xml";
    /**
     * RSS feeds<br>
     *
     * <br>
     * MediaType: <i>application/rss+xml</i>
     * <br>
     * FileSuffix: <i>.rss</i>
     */
    public static final String APPLICATION_RSS_XML = "application/rss+xml";
    /**
     * For download apk files.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.android.package-archive</i>
     * <br>
     * FileSuffix: <i>.apk</i>
     */
    public static final String APPLICATION_VND_ANDROID_PACKAGE_ARCHIVE = "application/vnd.android.package-archive";
    /**
     * deb (file format), a software package format used by the Debian project<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/vnd.debian.binary-package</i>
     * <br>
     * FileSuffix: <i>.deb</i>
     */
    public static final String APPLICATION_VND_DEBIAN_BINARY_PACKAGE = "application/vnd.debian.binary-package";
    /**
     * KML files (e.g. for Google Earth)<br>
     *
     * <br>
     * MediaType: <i>application/vnd.google-earth.kml+xml</i>
     * <br>
     * FileSuffix: <i>.kml</i>
     */
    public static final String APPLICATION_VND_GOOGLE_EARTH_KML_XML = "application/vnd.google-earth.kml+xml";
    /**
     * KMZ files (e.g. for Google Earth)<br>
     *
     * <br>
     * MediaType: <i>application/vnd.google-earth.kmz</i>
     * <br>
     * FileSuffix: <i>.kmz</i>
     */
    public static final String APPLICATION_VND_GOOGLE_EARTH_KMZ = "application/vnd.google-earth.kmz";
    /**
     * Mozilla XUL files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.mozilla.xul+xml</i>
     * <br>
     * FileSuffix: <i>.xul</i>
     */
    public static final String APPLICATION_VND_MOZILLA_XUL_XML = "application/vnd.mozilla.xul+xml";
    /**
     * Microsoft Excel files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.ms-excel</i>
     * <br>
     * FileSuffix: <i>.xls</i>
     */
    public static final String APPLICATION_VND_MS_EXCEL = "application/vnd.ms-excel";
    /**
     * Microsoft Powerpoint files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.ms-powerpoint</i>
     * <br>
     * FileSuffix: <i>.ppt</i>
     */
    public static final String APPLICATION_VND_MS_POWERPOINT = "application/vnd.ms-powerpoint";
    /**
     * XPS document<br>
     *
     * <br>
     * MediaType: <i>application/vnd.ms-xpsdocument</i>
     * <br>
     * FileSuffix: <i>.xps</i>
     */
    public static final String APPLICATION_VND_MS_XPSDOCUMENT = "application/vnd.ms-xpsdocument";
    /**
     * OpenDocument Graphics<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/vnd.oasis.opendocument.graphics</i>
     * <br>
     * FileSuffix: <i>.odg</i>
     */
    public static final String APPLICATION_VND_OASIS_OPENDOCUMENT_GRAPHICS = "application/vnd.oasis.opendocument.graphics";
    /**
     * OpenDocument Presentation<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/vnd.oasis.opendocument.presentation</i>
     * <br>
     * FileSuffix: <i>.odp</i>
     */
    public static final String APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION = "application/vnd.oasis.opendocument.presentation";
    /**
     * OpenDocument Spreadsheet<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/vnd.oasis.opendocument.spreadsheet</i>
     * <br>
     * FileSuffix: <i>.ods</i>
     */
    public static final String APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET = "application/vnd.oasis.opendocument.spreadsheet";
    /**
     * OpenDocument Text<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/vnd.oasis.opendocument.text</i>
     * <br>
     * FileSuffix: <i>.odt</i>
     */
    public static final String APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT = "application/vnd.oasis.opendocument.text";
    /**
     * Microsoft Powerpoint 2007 files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.openxmlformats-officedocument.presentationml.presentation</i>
     * <br>
     * FileSuffix: <i>.pptx</i>
     */
    public static final String APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    /**
     * Microsoft Excel 2007 files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.openxmlformats-officedocument.spreadsheetml.sheet</i>
     * <br>
     * FileSuffix: <i>.xlsx</i>
     */
    public static final String APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    /**
     * Microsoft Word 2007 files<br>
     *
     * <br>
     * MediaType: <i>application/vnd.openxmlformats-officedocument.wordprocessingml.document</i>
     * <br>
     * FileSuffix: <i>.docx</i>
     */
    public static final String APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    /**
     * 7-Zip compression format.<br>
     *
     * <br>
     * MediaType: <i>application/x-7z-compressed</i>
     * <br>
     * FileSuffix: <i>.7z</i>
     */
    public static final String APPLICATION_X_7Z_COMPRESSED = "application/x-7z-compressed";
    /**
     * Google Chrome/Chrome OS extension, app, or theme package<br>
     *
     * <br>
     * MediaType: <i>application/x-chrome-extension</i>
     * <br>
     * FileSuffix: <i>.crx</i>
     */
    public static final String APPLICATION_X_CHROME_EXTENSION = "application/x-chrome-extension";
    /**
     * device-independent document in DVI format<br>
     *
     * <br>
     * MediaType: <i>application/x-dvi</i>
     * <br>
     * FileSuffix: <i>.dvi</i>
     */
    public static final String APPLICATION_X_DVI = "application/x-dvi";
    /**
     * TrueType Font No registered MIME type, but this is the most commonly used<br>
     *
     * <br>
     * MediaType: <i>application/x-font-ttf</i>
     * <br>
     * FileSuffix: <i>.ttf</i>
     */
    public static final String APPLICATION_X_FONT_TTF = "application/x-font-ttf";
    /**
     * LaTeX files<br>
     *
     * <br>
     * MediaType: <i>application/x-latex</i>
     * <br>
     * FileSuffix: <i>.tex</i>
     */
    public static final String APPLICATION_X_LATEX = "application/x-latex";
    /**
     * .m3u8 variant playlist<br>
     *
     * <br>
     * MediaType: <i>application/x-mpegURL</i>
     * <br>
     * FileSuffix: <i>.m3u8</i>
     */
    public static final String APPLICATION_X_MPEGURL = "application/x-mpegURL";
    /**
     * a variant of PKCS standard files<br>
     *
     * <br>
     * MediaType: <i>application/x-pkcs12</i>
     * <br>
     * FileSuffix: <i>.p12</i>
     */
    public static final String APPLICATION_X_PKCS12 = "application/x-pkcs12";
    /**
     * RAR archive files<br>
     *
     * <br>
     * MediaType: <i>application/x-rar-compressed</i>
     * <br>
     * FileSuffix: <i>.rar</i>
     */
    public static final String APPLICATION_X_RAR_COMPRESSED = "application/x-rar-compressed";
    /**
     * Adobe Flash files for example with the extension .swf<br>
     *
     * <br>
     * MediaType: <i>application/x-shockwave-flash</i>
     * <br>
     * FileSuffix: <i>.swf</i>
     */
    public static final String APPLICATION_X_SHOCKWAVE_FLASH = "application/x-shockwave-flash";
    /**
     * StuffIt archive files<br>
     *
     * <br>
     * MediaType: <i>application/x-stuffit</i>
     * <br>
     * FileSuffix: <i>.sit</i>
     */
    public static final String APPLICATION_X_STUFFIT = "application/x-stuffit";
    /**
     * Tarball files<br>
     *
     * <br>
     * MediaType: <i>application/x-tar</i>
     * <br>
     * FileSuffix: <i>.tar</i>
     */
    public static final String APPLICATION_X_TAR = "application/x-tar";
    /**
     * Add-ons to Mozilla applications (Firefox, Thunderbird, SeaMonkey, and the discontinued Sunbird)<br>
     *
     * <br>
     * MediaType: <i>application/x-xpinstall</i>
     * <br>
     * FileSuffix: <i>.xpi</i>
     */
    public static final String APPLICATION_X_XPINSTALL = "application/x-xpinstall";
    /**
     * Markup language for Microsoft applications.<br>
     *
     * Vectorgrafic.<br>
     *
     * <br>
     * MediaType: <i>application/xaml+xml</i>
     * <br>
     * FileSuffix: <i>.xaml</i>
     */
    public static final String APPLICATION_XAML_XML = "application/xaml+xml";
    /**
     * XHTML<br>
     *
     * Defined by RFC 3236<br>
     *
     * <br>
     * MediaType: <i>application/xhtml+xml</i>
     * <br>
     * FileSuffix: <i>.xhtml</i>
     */
    public static final String APPLICATION_XHTML_XML = "application/xhtml+xml";
    /**
     * DTD files<br>
     *
     * Defined by RFC 3023<br>
     *
     * <br>
     * MediaType: <i>application/xml-dtd</i>
     * <br>
     * FileSuffix: <i>.dtd</i>
     */
    public static final String APPLICATION_XML_DTD = "application/xml-dtd";
    /**
     * XML files<br>
     *
     * Defined by RFC 3023<br>
     *
     * <br>
     * MediaType: <i>application/xml</i>
     * <br>
     * FileSuffix: <i>.xml</i>
     */
    public static final String APPLICATION_XML = "application/xml";
    /**
     * XOP<br>
     *
     * <br>
     * MediaType: <i>application/xop+xml</i>
     * <br>
     * FileSuffix: <i>.xop</i>
     */
    public static final String APPLICATION_XOP_XML = "application/xop+xml";
    /**
     * ZIP archive files<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>application/zip</i>
     * <br>
     * FileSuffix: <i>.zip</i>
     */
    public static final String APPLICATION_ZIP = "application/zip";
    /**
     * μ-law audio at 8 kHz, 1 channel<br>
     *
     * Defined in RFC 2046<br>
     *
     * <br>
     * MediaType: <i>audio/basic</i>
     * <br>
     * FileSuffix: <i>.au</i>
     */
    public static final String AUDIO_BASIC = "audio/basic";
    /**
     * native Flac (Flac in its own container)<br>
     *
     * <br>
     * MediaType: <i>audio/flac</i>
     * <br>
     * FileSuffix: <i>.flac</i>
     */
    public static final String AUDIO_FLAC = "audio/flac";
    /**
     * MP4 audio<br>
     *
     * <br>
     * MediaType: <i>audio/mp4</i>
     * <br>
     * FileSuffix: <i>.mp4, .m4a, .m4p, .m4b, .m4r, .m4v</i>
     */
    public static final String AUDIO_MP4 = "audio/mp4";
    /**
     * MP3 or other MPEG audio<br>
     *
     * Defined in RFC 3003<br>
     *
     * <br>
     * MediaType: <i>audio/mpeg</i>
     * <br>
     * FileSuffix: <i>.mpeg, .mpg, .mp3</i>
     */
    public static final String AUDIO_MPEG = "audio/mpeg";
    /**
     * Vorbis, Opus, Speex, Flac and other audio in an Ogg container<br>
     *
     * Defined in RFC 5334<br>
     *
     * <br>
     * MediaType: <i>audio/ogg</i>
     * <br>
     * FileSuffix: <i>.ogg, .oga, .ogx, .ogm, .spx, .opus</i>
     */
    public static final String AUDIO_OGG = "audio/ogg";
    /**
     * RealAudio<br>
     *
     * Documented in RealPlayer Help<br>
     *
     * <br>
     * MediaType: <i>audio/vnd.rn-realaudio</i>
     * <br>
     * FileSuffix: <i>.ra, .ram</i>
     */
    public static final String AUDIO_VND_RN_REALAUDIO = "audio/vnd.rn-realaudio";
    /**
     * WAV audio<br>
     *
     * Defined in RFC 2361<br>
     *
     * <br>
     * MediaType: <i>audio/vnd.wave</i>
     * <br>
     * FileSuffix: <i>.wav, .wave</i>
     */
    public static final String AUDIO_VND_WAVE = "audio/vnd.wave";
    /**
     * WebM open media format<br>
     *
     * <br>
     * MediaType: <i>audio/webm</i>
     * <br>
     * FileSuffix: <i>.webm</i>
     */
    public static final String AUDIO_WEBM = "audio/webm";
    /**
     * .aac audio files<br>
     *
     * <br>
     * MediaType: <i>audio/x-aac</i>
     * <br>
     * FileSuffix: <i>.aac</i>
     */
    public static final String AUDIO_X_AAC = "audio/x-aac";
    /**
     * Apple's CAF audio files<br>
     *
     * <br>
     * MediaType: <i>audio/x-caf</i>
     * <br>
     * FileSuffix: <i>.caf</i>
     */
    public static final String AUDIO_X_CAF = "audio/x-caf";
    /**
     * GIF image<br>
     *
     * Defined in RFC 2045 and RFC 2046<br>
     *
     * <br>
     * MediaType: <i>image/gif</i>
     * <br>
     * FileSuffix: <i>.gif</i>
     */
    public static final String IMAGE_GIF = "image/gif";
    /**
     * JPEG JFIF image<br>
     *
     * Defined in RFC 2045 and RFC 2046<br>
     *
     * <br>
     * MediaType: <i>image/jpeg</i>
     * <br>
     * FileSuffix: <i>.jpg, .jpeg, .jpe, .jif, .jfif, .jfi</i>
     */
    public static final String IMAGE_JPEG = "image/jpeg";
    /**
     * Portable Network Graphics<br>
     *
     * Registered, Defined in RFC 2083<br>
     *
     * <br>
     * MediaType: <i>image/png</i>
     * <br>
     * FileSuffix: <i>.png</i>
     */
    public static final String IMAGE_PNG = "image/png";
    /**
     * SVG vector image<br>
     *
     * Defined in SVG Tiny 1.2 Specification Appendix M<br>
     *
     * <br>
     * MediaType: <i>image/svg+xml</i>
     * <br>
     * FileSuffix: <i>.svg</i>
     */
    public static final String IMAGE_SVG_XML = "image/svg+xml";
    /**
     * TIF image<br>
     *
     * <br>
     * MediaType: <i>image/tiff</i>
     * <br>
     * FileSuffix: <i>.tif, .tiff</i>
     */
    public static final String IMAGE_TIFF = "image/tiff";
    /**
     * DjVu image and multipage document format.<br>
     *
     * <br>
     * MediaType: <i>image/vnd.djvu</i>
     * <br>
     * FileSuffix: <i>.djv, .djvu</i>
     */
    public static final String IMAGE_VND_DJVU = "image/vnd.djvu";
    /**
     * A raster graphics file format created by Truevision Inc.<br>
     *
     * Not registered at IANA.<br>
     *
     * <br>
     * MediaType: <i>image/x-tga</i>
     * <br>
     * FileSuffix: <i>.tga</i>
     */
    public static final String IMAGE_X_TGA = "image/x-tga";
    /**
     * GIMP image file<br>
     *
     * <br>
     * MediaType: <i>image/x-xcf</i>
     * <br>
     * FileSuffix: <i>.xcf</i>
     */
    public static final String IMAGE_X_XCF = "image/x-xcf";
    /**
     * Email<br>
     *
     * EML files, MIME files, MHT files, MHTML files<br>
     *
     * Defined in RFC 2045 and RFC 2046<br>
     *
     * <br>
     * MediaType: <i>message/rfc822</i>
     * <br>
     * FileSuffix: <i>.eml, .mht, .mhtml, .nws</i>
     */
    public static final String MESSAGE_RFC822 = "message/rfc822";
    /**
     * IGS files, IGES files<br>
     *
     * Defined in RFC 2077<br>
     *
     * <br>
     * MediaType: <i>model/iges</i>
     * <br>
     * FileSuffix: <i>.igs, .iges</i>
     */
    public static final String MODEL_IGES = "model/iges";
    /**
     * MSH files, MESH files<br>
     *
     * Defined in RFC 2077, SILO files<br>
     *
     * <br>
     * MediaType: <i>model/mesh</i>
     * <br>
     * FileSuffix: <i>.msh, .mesh</i>
     */
    public static final String MODEL_MESH = "model/mesh";
    /**
     * WRL files, VRML files<br>
     *
     * Defined in RFC 2077<br>
     *
     * <br>
     * MediaType: <i>model/vrml</i>
     * <br>
     * FileSuffix: <i>.wrl, .wrml</i>
     */
    public static final String MODEL_VRML = "model/vrml";
    /**
     * iCalendar<br>
     *
     * The file format for calendar data exchange<br>
     *
     * <br>
     * MediaType: <i>text/calendar</i>
     * <br>
     * FileSuffix: <i>.ics, .ical, .ifb, .icalendar</i>
     */
    public static final String TEXT_CALENDAR = "text/calendar";
    /**
     * Cascading Style Sheets<br>
     *
     * Defined in RFC 2318<br>
     *
     * <br>
     * MediaType: <i>text/css</i>
     * <br>
     * FileSuffix: <i>.css</i>
     */
    public static final String TEXT_CSS = "text/css";
    /**
     * Comma-separated values<br>
     *
     * Defined in RFC 4180<br>
     *
     * <br>
     * MediaType: <i>text/csv</i>
     * <br>
     * FileSuffix: <i>.csv</i>
     */
    public static final String TEXT_CSV = "text/csv";
    /**
     * HTML<br>
     *
     * Defined in RFC 2854<br>
     *
     * <br>
     * MediaType: <i>text/html</i>
     * <br>
     * FileSuffix: <i>.htm, .html</i>
     */
    public static final String TEXT_HTML = "text/html";
    /**
     * Textual data<br>
     *
     * Defined in RFC 2046 and RFC 3676<br>
     *
     * <br>
     * MediaType: <i>text/plain</i>
     * <br>
     * FileSuffix: <i>.txt, .text</i>
     */
    public static final String TEXT_PLAIN = "text/plain";
    /**
     * RTF<br>
     *
     * Defined by Paul Lindner<br>
     *
     * <br>
     * MediaType: <i>text/rtf</i>
     * <br>
     * FileSuffix: <i>.rtf</i>
     */
    public static final String TEXT_RTF = "text/rtf";
    /**
     * vCard (contact information)<br>
     *
     * Defined in RFC 6350<br>
     *
     * <br>
     * MediaType: <i>text/vcard</i>
     * <br>
     * FileSuffix: <i>.vcard</i>
     */
    public static final String TEXT_VCARD = "text/vcard";
    /**
     * ABC music notation<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>text/vnd.abc</i>
     * <br>
     * FileSuffix: <i>.abc</i>
     */
    public static final String TEXT_VND_ABC = "text/vnd.abc";
    /**
     * Markdown formatted text<br>
     *
     * <br>
     * MediaType: <i>text/x-markdown</i>
     * <br>
     * FileSuffix: <i>.md</i>
     */
    public static final String TEXT_X_MARKDOWN = "text/x-markdown";
    /**
     * Covers most Windows-compatible formats including .avi and .divx<br>
     *
     * <br>
     * MediaType: <i>video/avi</i>
     * <br>
     * FileSuffix: <i>.avi</i>
     */
    public static final String VIDEO_AVI = "video/avi";
    /**
     * MP4 video<br>
     *
     * Defined in RFC 4337<br>
     *
     * <br>
     * MediaType: <i>video/mp4</i>
     * <br>
     * FileSuffix: <i>.mp4</i>
     */
    public static final String VIDEO_MP4 = "video/mp4";
    /**
     * MPEG-1 video with multiplexed audio<br>
     *
     * Defined in RFC 2045 and RFC 2046<br>
     *
     * <br>
     * MediaType: <i>video/mpeg</i>
     * <br>
     * FileSuffix: <i>.mpeg</i>
     */
    public static final String VIDEO_MPEG = "video/mpeg";
    /**
     * Ogg Theora or other video (with audio)<br>
     *
     * Defined in RFC 5334<br>
     *
     * <br>
     * MediaType: <i>video/ogg</i>
     * <br>
     * FileSuffix: <i>.ogv</i>
     */
    public static final String VIDEO_OGG = "video/ogg";
    /**
     * QuickTime video<br>
     *
     * Registered<br>
     *
     * <br>
     * MediaType: <i>video/quicktime</i>
     * <br>
     * FileSuffix: <i>.mov, .qt</i>
     */
    public static final String VIDEO_QUICKTIME = "video/quicktime";
    /**
     * WebM Matroska-based open media format<br>
     *
     * <br>
     * MediaType: <i>video/webm</i>
     * <br>
     * FileSuffix: <i>.webm</i>
     */
    public static final String VIDEO_WEBM = "video/webm";
    /**
     * Flash video (FLV files)<br>
     *
     * <br>
     * MediaType: <i>video/x-flv</i>
     * <br>
     * FileSuffix: <i>.flv, .f4v, .f4p, .f4a, .f4b</i>
     */
    public static final String VIDEO_X_FLV = "video/x-flv";
    /**
     * Matroska open media format<br>
     *
     * <br>
     * MediaType: <i>video/x-matroska</i>
     * <br>
     * FileSuffix: <i>.mkv, .mk3d, .mka, .mks</i>
     */
    public static final String VIDEO_X_MATROSKA = "video/x-matroska";
    /**
     * Windows Media Video<br>
     *
     * Documented in Microsoft KB 288102<br>
     *
     * <br>
     * MediaType: <i>video/x-ms-wmv</i>
     * <br>
     * FileSuffix: <i>.wmv</i>
     */
    public static final String VIDEO_X_MS_WMV = "video/x-ms-wmv";
}
