package nu.hex.mediatype;

/**
 *
 * DO NOT MODIFY! This interface is autogenerated.
 *
 * Changes done here will be owerwritten the next time the project runs.
 *
 * To add mediatypes or edit them, run this project and use the editor.
 *
 * If the MTD is manually edited, run the project and use the update button.
 *
 * To remove a mediatype, remove it manually from the MTD file.
 *
 */
public interface HexMediaType {

    /**
     * Kapmanj-format<br>
     *
     * XML-format för RPG-kampanjdata.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.hex.campaign.hrmx+xml</i>
     * <br>
     * FileSuffix: <i>.hrmx</i>
     */
    public static final String APPLICATION_VND_HEX_CAMPAIGN_HRMX_XML = "application/vnd.hex.campaign.hrmx+xml";
}
