package nu.hex.mediatype;

/**
 *
 * DO NOT MODIFY! This interface is autogenerated.
 *
 * Changes done here will be owerwritten the next time the project runs.
 *
 * To add mediatypes or edit them, run this project and use the editor.
 *
 * If the MTD is manually edited, run the project and use the update button.
 *
 * To remove a mediatype, remove it manually from the MTD file.
 *
 */
public interface HexMediaType {

    /**
     * Compressed Music Project format<br>
     *
     * Compressed Format for Music Projects.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.hex.amx</i>
     * <br>
     * FileSuffix: <i>.amx</i>
     */
    public static final String APPLICATION_VND_HEX_AMX = "application/vnd.hex.amx";
    /**
     * Music Project format<br>
     *
     * XML Format for Music Projects.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.hex.amxf+xml</i>
     * <br>
     * FileSuffix: <i>.amxf</i>
     */
    public static final String APPLICATION_VND_HEX_AMXF_XML = "application/vnd.hex.amxf+xml";
    /**
     * Campaign Project format<br>
     *
     * Compressed format for RPG Campaign projects.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.hex.hrm+zip</i>
     * <br>
     * FileSuffix: <i>.hrm</i>
     */
    public static final String APPLICATION_VND_HEX_HRM_ZIP = "application/vnd.hex.hrm+zip";
    /**
     * Campaign Project format<br>
     *
     * XML format for RPG Campaign projects.<br>
     *
     * <br>
     * MediaType: <i>application/vnd.hex.hrmx+xml</i>
     * <br>
     * FileSuffix: <i>.hrmx</i>
     */
    public static final String APPLICATION_VND_HEX_HRMX_XML = "application/vnd.hex.hrmx+xml";
}
